const { urlencoded } = require('body-parser');
const express = require('express');
const router = express.Router();
const controller = require("../controllers/controller.js");

router.get('/home', controller.home);
router.get('/pharmacy_order', controller.pharmacy_order);
router.get('/pharmacy_order_add', controller.pharmacy_order_add);
router.get('/medicine', controller.medicine);
router.post('/medicine', controller.medicine_search);
router.get('/medicine_add', controller.medicine_add_form);
router.post('/medicine_add', controller.medicine_add);
router.get('/medicine_edit/:medicine_id', controller.medicine_edit_form);
router.post('/medicine_edit/:medicine_id', controller.medicine_edit);
router.get('/medicine_delete/:medicine_id', controller.medicine_delete);
router.get('/supplier', controller.supplier);
router.post('/supplier', controller.supplier_search);
router.get('/supplier_add', controller.supplier_add_form);
router.post('/supplier_add', controller.supplier_add);
router.get('/supplier_edit/:supplier_id', controller.supplier_edit_form);
router.post('/supplier_edit/:supplier_id', controller.supplier_edit);
router.get('/supplier_delete/:supplier_id', controller.supplier_delete);
router.get('/storage', controller.storage);
router.post('/storage', controller.storage_search);
router.get('/storage_add', controller.storage_add_form);
router.post('/storage_add', controller.storage_add);
router.get('/storage_view/:storage_id', controller.storage_view);
router.get('/storage_edit/:storage_id', controller.storage_edit_form);
router.post('/storage_edit/:storage_id', controller.storage_edit);
router.get('/storage_delete/:storage_id', controller.storage_delete);
router.get('/internet_orders', controller.internet_orders);
router.post('/internet_orders', controller.internet_orders_search);
router.get('/internet_orders_search_delete/:client_order_id', controller.internet_orders_search_delete);
router.get('/internet_orders_cheque/:order_number', controller.internet_orders_search);
router.get('/new_order', controller.new_order);
router.post('/new_order', controller.new_order_search);
router.get('/new_order_add/:storage_id', controller.new_order_add_form);
router.post('/new_order_add/:storage_id', controller.new_order_add);
router.get('/new_order_cheque', controller.new_order_cheque);
router.get('/new_order_change_amount/:client_order_id', controller.new_order_change_amount_form)
router.post('/new_order_change_amount/:client_order_id', controller.new_order_change_amount);
router.get('/new_order_cheque_result', controller.new_order_cheque_result);
router.post('/new_order_cheque_result', controller.new_order_cheque_result);
//router.post('/new_order_cheque', controller.new_order_cheque);
//router.post('/internet_orders_cheque/:order_number', controller.internet_orders_search);
//router.get('/internet_orders_sum', controller.internet_orders_sum_form);
//router.get('/internet_orders_sum/:number_order', controller.internet_orders_sum);
//router.post('/internet_orders_sum/:number_order', controller.internet_orders_sum_form);

module.exports = router;